CREATE TABLE IF NOT EXISTS page
(id SERIAL PRIMARY KEY,
site_id INT NOT NULL,
path TEXT NOT NULL,
code INT NOT NULL,
content TEXT NOT NULL,
FOREIGN KEY (site_id) REFERENCES site(id) ON DELETE RESTRICT);