CREATE TABLE IF NOT EXISTS index
(id SERIAL PRIMARY KEY,
page_id INT NOT NULL,
lemma_id INT NOT NULL,
rank FLOAT NOT NULL,
FOREIGN KEY (page_id) REFERENCES page(id) ON DELETE RESTRICT,
FOREIGN KEY (lemma_id) REFERENCES lemma(id));