CREATE TABLE `lemma`
(`id` INT NOT NULL AUTO_INCREMENT,
`site_id` INT NOT NULL,
`lemma` VARCHAR(255) NOT NULL,
`frequency` INT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (site_id) REFERENCES site(id) ON DELETE CASCADE);