CREATE TABLE `page`
(`id` INT NOT NULL AUTO_INCREMENT,
`site_id` INT NOT NULL,
`path` TEXT NOT NULL,
`code` INT NOT NULL,
`content` MEDIUMTEXT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (site_id) REFERENCES site(id) ON DELETE CASCADE);